// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC77zi9EMSekmi7iFjKZsJSTi1sBnCjOWI',
    appId: '1:645479269287:web:d071b975f6892c67b9ac82',
    messagingSenderId: '645479269287',
    projectId: 'about-chicken',
    authDomain: 'about-chicken.firebaseapp.com',
    storageBucket: 'about-chicken.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTwd4iJEU9P9lOZ2Ypbz0dPlQLteLZ0XM',
    appId: '1:645479269287:android:fbc7ace07969327fb9ac82',
    messagingSenderId: '645479269287',
    projectId: 'about-chicken',
    storageBucket: 'about-chicken.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ7Xx-WJchTRBmlonSVi91MbdJOGXzxsc',
    appId: '1:645479269287:ios:0f9e917c824627feb9ac82',
    messagingSenderId: '645479269287',
    projectId: 'about-chicken',
    storageBucket: 'about-chicken.firebasestorage.app',
    iosBundleId: 'com.example.aboutChicken',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ7Xx-WJchTRBmlonSVi91MbdJOGXzxsc',
    appId: '1:645479269287:ios:0f9e917c824627feb9ac82',
    messagingSenderId: '645479269287',
    projectId: 'about-chicken',
    storageBucket: 'about-chicken.firebasestorage.app',
    iosBundleId: 'com.example.aboutChicken',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC77zi9EMSekmi7iFjKZsJSTi1sBnCjOWI',
    appId: '1:645479269287:web:e512831594ab3a9db9ac82',
    messagingSenderId: '645479269287',
    projectId: 'about-chicken',
    authDomain: 'about-chicken.firebaseapp.com',
    storageBucket: 'about-chicken.firebasestorage.app',
  );
}
